# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"

    before_all do
    #ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
    #ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "180"

    @workspace_path = "./Demo.xcworkspace"
    @project_path = "./Demo.xcodeproj"
    @plist_path = "Demo/Info.plist"
    
    @scheme = "Demo"

    #@is_cron_job = ENV["TRAVIS_EVENT_TYPE"] == "cron" # if job is fired as a CRON job, this means we want to run full test suite and don't deploy
  end

  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  desc "Runs unit tests"
  private_lane :run_unit_tests do |options|
    scan(
      workspace: @workspace_path,
      scheme: @scheme,
      #skip_slack: true,
      xcargs: @xcargs,
      derived_data_path: @derived_data_path
    )
  end


  lane :beta do
  increment_build_number
  build_app
  upload_to_testflight
  end

  lane :deploy do
    run_unit_tests
    increment_build_number
    #build_app
    #upload_to_testflight
  end

  lane :release do
    capture_screenshots
    build_app
    upload_to_app_store       # Upload the screenshots and the binary to iTunes
    slack                     # Let your team-mates know the new version is live
  end

end
